dist: trusty
language: generic
services: docker
sudo: required

env:
  global:
    # Default target on travis-ci.
    # Used as conditional check in the install stage
    - HOST=x86_64-unknown-linux-gnu
    - PROJECT_NAME=zoom-fix

cache:
  directories:
    - $HOME/.cargo
    - $TRAVIS_BUILD_DIR/target

matrix:
  include:
    # Linux
    - os: linux
      language: rust
      env:
        - TARGET=x86_64-unknown-linux-gnu
      script:
        - cargo build --release --target $TARGET --verbose

    # OSX
    - os: osx
      language: rust
      env: TARGET=x86_64-apple-darwin
      script:
        - cargo build --release --target $TARGET --verbose

    - os: windows
      language: rust
      env: TARGET=x86_64-pc-windows-msvc
      script:
        - cargo build --release --target $TARGET --verbose
      before_deploy:
        - powershell -executionpolicy bypass -File "ci\before_deploy.ps1"

before_install: true

before_deploy:
  - bash ci/before_deploy.sh

deploy:
  provider: releases
  api_key:
    # Generate secure token with travis encrypt --pro
    secure: "2XpYX2J8dIlq7HJ0iOzRZKRTDz7aKuTsdp0oTBLebCieM8CzfwT3mQ/3jB+shtSc3iVlSWBD81yE0MZ22aQ4F3q2CVjIgLkv8nJR5xKQ3ugP/vfWmiu6JW19bEBgREdERzxvlrwxoOrFcrCOSzSiHCokLnaDjMcsQG+DJvePXCklsPfqlsuuBfZK9h84fG+dMmY++Qh9r7MSzVgWHDebgzkqBcAyNcHdqzLj7mUnWdrmwvIBoFyIJGWoJ/sqtT3v4jJGXT8y0VONQYiHtN9b8rB1y9lJLQVQEzGVe6gMV4Qg5+gWOOPNhYoWWhOs6FBiKF9IHEXN7pheQ11jL5+WXMQMgUbxDVQPXAEYqtaIJsSO5uN11RAPopekRVYLtndNqWAaMlUYkhsmbLmpu4Ef6nZwMHTlW+W1YcN6l4GNVemtGLQCOFRZ5sNulsGKqwl7puKp/wO96iPmNOBNhuMHX+UGAWAzs+TU+ZcSouFqKGLToNbx2giSAGY3V/AwjLo2MQdGuPLNlPgSovUpN98tpAFZTRZOa6S+Jb5T5u+g5Fuiz1AllHUxOsVjLt7QdZuKGu2jvJyaIq+gdoLn+Vtiea7/ilV1g2bDg9bJ4VMvLn04ZWbH57HG1mmSkHFO/m+Zmm3yKwVs5/D2dJuw0ZzSltIkRB6sfXhFkAxjV239ZeI="
  file_glob: true
  file: $PROJECT_NAME-$TRAVIS_TAG-$TARGET.*
  skip_cleanup: true

before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    - "/^v\\d+\\.\\d+\\.\\d+.*$/"
    - master

notifications:
  email:
    on_success: never
